---
title: Analysis of Australia's Higher Education Loan Program
  (HELP) Statistics
author: "Alana Dabelstein, Anh-Thu Hoang, Chenxi Zhang"
date: "01/06/2023"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: paper
    fig_width: 7
    fig_height: 4
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Loading Libraries
library(readxl)

# Loading Data
table_1 <- read_xlsx("Data/help-statistics-2021-2022.xlsx", sheet = 2, skip = 2, col_names = TRUE)
table_2 <- read_xlsx("Data/help-statistics-2021-2022.xlsx", sheet = 3, skip = 2, col_names = TRUE)
table_3 <- read_xlsx("Data/help-statistics-2021-2022.xlsx", sheet = 4, skip = 2, col_names = TRUE)
table_4 <- read_xlsx("Data/help-statistics-2021-2022.xlsx", sheet = 5, skip = 2, col_names = TRUE)
table_7 <- read_xlsx("Data/help-statistics-2021-2022.xlsx", sheet = 8, skip = 2, col_names = TRUE)
```

## Introduction

## Analysis

### Alana's Part

1. How does total outstanding debt and number of debtors change from the financial years 2005-06 to 2021-22? 

```{r loading, include=FALSE, message=FALSE, warning=FALSE}
table_8 <- read.csv("Data/HELP_DATA_TIDIED.csv")

library(tidyverse)
library(gridExtra)
library(knitr)
library(bookdown)
library(eeptools)
```

```{r table1, message=FALSE, warning=FALSE, include=FALSE}
# Group By Year 
table_8_year <- table_8 %>%
  group_by(Year) %>%
  summarise(`Total Number of Debtors (millions)` = sum(Num_Debtors)/1000000, 
            `Total Outstanding Debt (billions $)` = sum(Outstanding_Debt)/1000000000) 

# Create Table
kable(table_8_year, 
      caption = "Total Debtors (in millions) and Total Oustanding Debt (in billions)",
             digits = 2)
```

```{r figure1, warning=FALSE, message=FALSE, include=FALSE, fig.align='center', fig.cap="Total outstanding debt and number of debtors from the financial years 2005-06 to 2021-22"}
totalOut_plot <- ggplot(data = table_8_year, aes(x = Year, y = `Total Outstanding Debt (billions $)`)) + 
  geom_point(alpha = 0.8) + 
  xlab("Year") + 
  ylab("Total Oustanding Debt ($) in billions") + 
  labs(title = "a) Outstanding Debt Has Rapidly Increased From 2005", subtitle = "Total Outstanding Debt From 2005-2021") +
  theme_minimal() +  
  geom_smooth()  + 
  scale_y_continuous(labels = scales::comma)

totalDebtors_plot <- ggplot(data = table_8_year, aes(x = Year, y = `Total Number of Debtors (millions)`)) + 
  geom_point(alpha = 0.8) + 
  xlab("Year") + 
  ylab("Total Debtors in millions") + 
  labs(title = "b) Number of Debtors Has Rapidly Increased From 2005", subtitle = "Total Number of Debtors From 2005-2021") +
  theme_minimal() +  
  geom_smooth()  + 
  scale_y_continuous(labels = scales::comma)


grid.arrange(totalOut_plot, totalDebtors_plot, nrow = 2)
```

2. Which groups are at risk of high debt? 

```{r table2, include=FALSE, message=FALSE, warning=FALSE}
# Group By Year 
table_8_sex <- table_8 %>%
  group_by(Sex) %>%
  summarise(`Mean Number of Debtors` = mean(Num_Debtors), 
            `Mean Outstanding Debt (in billions)` = mean(Outstanding_Debt)/1000000000)

kable(table_8_sex, 
      caption = "Average Debtors and Outstanding Debt By Sex from 2005-2021",
             digits = 2)
```

```{r figure2, include=FALSE, message=FALSE, warning=FALSE, fig.align='center'}
table_8_sex_year <- table_8 %>%
  group_by(Sex, Year) %>%
  summarise(mean_number_Debtors = mean(Num_Debtors), 
            mean_outstandingDebt_billions = mean(Outstanding_Debt)/1000000000)


plot3 <- ggplot(data = table_8_sex_year, aes(x = Year, y = mean_number_Debtors, col = Sex)) + 
  geom_point(alpha = 0.8) + 
  xlab("Year") + 
  ylab("Mean Number of Debtors") + 
  labs(title = "a) There is an Increase in Both Male and Female Debtors", subtitle = "Females on average are more likely to be in debt") +
  theme_minimal() +  
  geom_smooth()  + 
  scale_y_continuous(labels = scales::comma)


plot4 <- ggplot(data = table_8_sex_year, aes(x = Year, y = mean_outstandingDebt_billions, col = Sex)) + 
  geom_point(alpha = 0.8) + 
  xlab("Year") + 
  ylab("Mean Outstanding Debt ($) in billions") + 
  labs(title = "b) Females Have a Greater Outstanding Debt than Males", subtitle = "There is an increasing gap between outstanding debt by sex") +
  theme_minimal() +  
  geom_smooth()  + 
  scale_y_continuous(labels = scales::comma)

grid.arrange(plot3, plot4, nrow = 2)

```

Looking at Ages:

```{r table3, include=FALSE, message=FALSE, warning=FALSE}
# group by age 

table_8_age <- table_8 %>%
  group_by(Age_Range) %>%
  summarise(`Mean Number of Debtors (in thousands)` = mean(Num_Debtors)/1000, 
            `Mean Oustanding Debt (in millions)` = mean(Outstanding_Debt)/1000000)

kable(table_8_age, 
      caption = "Average Number of Debtors and Outstanding Debt by Age Group from 2005-2021",
             digits = 2)
```

```{r figure3, include=FALSE, message=FALSE, warning=FALSE, fig.align='center'}
# group by age and year 

table_8_age_year <- table_8 %>%
  group_by(Age_Range, Year) %>%
  filter(Age_Range != "Unknown") %>%
  summarise(mean_NumDebtors = mean(Num_Debtors), 
            mean_OustandingDebt = mean(Outstanding_Debt)) 

plot5 <- ggplot(data = table_8_age_year, aes(x = Year, y = mean_NumDebtors, col = Age_Range)) + 
  geom_point(alpha = 0.8) + 
  xlab("Year") + 
  ylab("Mean Number of Debtors") + 
  labs(title = "a) Ages 20-29 are the Largest Group of Debtors", subtitle = "Most age ranges have an increase in the number of debtors") +
  theme_minimal() +  
  geom_smooth()  + 
  scale_y_continuous(labels = scales::comma)

plot6 <- ggplot(data = table_8_age_year, aes(x = Year, y = mean_OustandingDebt, col = Age_Range)) + 
  geom_point(alpha = 0.8) + 
  xlab("Year") + 
  ylab("Mean Outstanding Debt ($)") + 
  labs(title = "b) Ages 20-29 Have the Highest Outstanding Debt", subtitle = "There is a rapid increase for ages 30-39") +
  theme_minimal() +  
  geom_smooth()  + 
  scale_y_continuous(labels = scales::comma)

grid.arrange(plot5, plot6, nrow = 2)
```

### Anh-Thu's Part

### Chenxi's Part

## Conclusion

## References

## Appendix
